services:
  # A Node service (backend)
  - type: web
    name: ndt-prod-backend1
    runtime: node
    repo: https://github.com/alejandro-mancebo/natural-disaster-track.git
    
  # A static web (frontend)
  - type: web
    name: ndt-prod-frontend1
    runtime: static
    repo: https://github.com/alejandro-mancebo/natural-disaster-track.git
   